In [ ]:
import numpy as np
a = np.arange(0, 100, 10)
lin_spaced = np.linspace(0, 100, 10, dtype=int)
b_float = np.arange(3, dtype=float)
char_arr = np.array(['Welcome to Math for ML!'])
print(a)
print(lin_spaced)
print(b_float)
print(a.dtype)
print(char_arr)
print(char_arr.dtype)


[ 0 10 20 30 40 50 60 70 80 90]
[  0  11  22  33  44  55  66  77  88 100]
[0. 1. 2.]
int64
['Welcome to Math for ML!']
<U23


In [25]:
ones_arr = np.ones(5)
print(ones_arr)

[1. 1. 1. 1. 1.]


In [26]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [27]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [28]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.7428996  0.10245258 0.80556004]


2D Arrays

In [29]:
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


Reshaping one dimensional arrays into multidimensions

In [37]:
one_dim = ([1,2,3,4,5,6])

reshape_dim = np.reshape(one_dim,(2,3))
print(reshape_dim)
print(reshape_dim.ndim)
print(reshape_dim.shape)
print(reshape_dim.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


Array math operations

In [40]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


Multiplying vector with a scalar (broadcasting) - Convert miles to kilometers

In [43]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

Indexing and slicing

In [54]:
a = ([2,7,8,3,6])
print(a[2])

8


In [56]:
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

print(two_dim[2][2])

9


In [66]:
a = ([2,7,9,6,3])
sliced_arr = a[:3]
print(sliced_arr)

sliced_arr1 = a[1:4]
print(sliced_arr1)

sliced_arr2 = a[::2]
print(sliced_arr2)

print(a == a[:] == a[::])

sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2, 7, 9]
[7, 9, 6]
[2, 9, 3]
True
[[4 5 6]
 [7 8 9]]
[2 5 8]


stacking

In [70]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')


a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [71]:
vertical_stack = np.vstack((a1, a2))
print(vertical_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [72]:
hori_stack = np.hstack((a1, a2))
print(hori_stack)

[[1 1 3 3]
 [2 2 4 4]]
