In [27]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

x = np.linalg.solve(A, b)

print(f"Solution: {x}")

d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

print(A_system[1])


Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]
Shape of A: (2, 2)
Shape of b: (2,)
Solution: [-1.  2.]
Determinant of matrix A: -11.00
[[-1.  3.  7.]
 [ 3.  2.  1.]]
[3. 2. 1.]


In [25]:
import numpy as np
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

A_2_system = np.hstack((A_2, b_2.reshape((2, 1))))
print(A_2_system)

Determinant of matrix A_2: 0.00
[[-1.  3.  7.]
 [ 3. -9.  1.]]


4 - System of Linear Equations with an Infinite Number of Solutions